# here are my aliases
alias lll='ls -lhaG'
alias xt='xfce4-terminal'
alias fb='sudo fb-messenger-cli'
alias ap='cd /etc/apache2'
alias wd='cd /var/www'
alias y='sudo mpsyt'
alias c='clear'
alias q='exit'
alias bq='exec bash'
alias gc='git commit -m'
alias gp='git push'
alias gst='git status'
alias ga='git add .'
alias phpini='sudo vim /etc/php/7.2/cli/php.ini'
alias ba='vim ~/.bash_aliases'
alias laravel='~/.composer/vendor/laravel/installer/bin/laravel'
alias goto_hs='cd /home/mabby/Documents/Projects/homestead/homestead/'

