#!/bin/bash

myDate(){
	myDate="$(date +"%a, %d %B")"
	echo "$myDate"
}
myTime() {
	myTime="$(date +"%H:%M")"
	echo "$myTime"
}

myBattery(){
	## get the battery info from acpi, then cut where there is a '%'
	# get the frist half of that string, then get the last 3 bytes using tail
	myBatteryPercentage="$(acpi | cut -d'%' -f 1 | tail -c -3)"

	echo "$(checkPlugStatus)"
	#echo "$myBatteryPercentage% $(checkPlugStatus)"
}

#vol="$(awk -F"[][]" '/dB/ { print $2 }' <(amixer sget Master))"
#vol="$(amixer get Master | awk '$0~/%/{print $4}' | tr -d '[]')"   

NETNAME=$(nmcli dev wifi | grep -E '^[*]' | awk '/*/ {print $3}')
NETBARS=$(nmcli dev wifi | grep -E '^[*]' | awk '/*/ {print $9}')
WET_STR="$(curl wttr.in?format=1)"
WEATHER="  ${WET_STR:1}"

if [[ $(nmcli radio wifi) == *"disabled"* ]]; then
	NETNAME="WIFI"
	NETBARS="OFF"
	WEATHER=""	
fi

#netlenc=$(nmcli dev wifi list | grep \* | cut -c27-50)


#xsetroot -name " kybrd: $(checkIbusLang) | $(awk -F"[][]" '/dB/ { print $2 }' <(amixer sget Master))  | $(myDate) | Btry:$(myBattery)"

vol="$(amixer get Master | awk '$0~/%/{print $4}' | tr -d '[]' | sed 's/.$//')"
if [[ $vol -ge 65 ]]; then
	vol_str=""
elif [[ $vol -ge 1 ]]; then
	vol_str=""
else
	vol_str=""
fi 

wet="${WEATHER:1}"
xsetroot -name " $NETNAME $NETBARS      $(checkIbusLang)     $(ramPercent)%    $vol_str $vol%    $(myBattery)     $(myTime)     $(myDate)  $WEATHER"


#expr length "$(nmcli dev wifi list)"

