#!/bin/bash

myDate(){
	myDate="$(date +"%H:%M %a, %d %B")"
	echo "$myDate"
}

myBattery(){
	## get the battery info from acpi, then cut where there is a '%'
	# get the frist half of that string, then get the last 3 bytes using tail
	myBatteryPercentage="$(acpi | cut -d'%' -f 1 | tail -c -3)"

	echo "$(checkPlugStatus)"
	#echo "$myBatteryPercentage% $(checkPlugStatus)"
}

#vol="$(awk -F"[][]" '/dB/ { print $2 }' <(amixer sget Master))"
#vol="$(amixer get Master | awk '$0~/%/{print $4}' | tr -d '[]')"   
NETNAME=$(nmcli dev wifi | grep -E '^[*]' | awk '/*/ {print $3}')
NETBARS=$(nmcli dev wifi | grep -E '^[*]' | awk '/*/ {print $9}')


#netlenc=$(nmcli dev wifi list | grep \* | cut -c27-50)


#xsetroot -name " kybrd: $(checkIbusLang) | $(awk -F"[][]" '/dB/ { print $2 }' <(amixer sget Master))  | $(myDate) | Btry:$(myBattery)"
vol="$(amixer get Master | awk '$0~/%/{print $4}' | tr -d '[]')" 
xsetroot -name " $NETNAME $NETBARS | $(checkIbusLang) | 🔈 $vol | $(myBattery) | $(tempCheck) | $(myDate)"


#expr length "$(nmcli dev wifi list)"

